name: Jekyll • Simple, blog-aware, static sites
description: Transform your plain text into static websites and blogs
# url: https://jekyllrb.com
# repository: https://github.com/jekyll/jekyll
timezone: America/Los_Angeles
logo: "/img/transperant_logo.png"
google_analytics_id: "UA-143724740-1"
google_site_verification: onQcXpAvtHBrUI5LlroHNE_FP0b2qvFyPq7VZw36iEY

# Build settings
markdown: kramdown
theme: minima
plugins:
- jekyll-avatar
- jekyll-feed
- jekyll-mentions
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
- jemoji

exclude:
- .gitignore
- .jekyll-cache
- CNAME
- readme.md

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

collections:
  # docs:
  #   permalink: "/:collection/:path/"
  #   output: true
  posts:
    permalink: "/blog/:title/"
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
