# config.yml

backend:
  name: github
  repo: jndctranslation/landing_page
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'img'

collections:
  - name: "setting"
    label: "Website setting"
    files:
      - label: "Web Information"
        name: "information"
        file: "_data/information.yml"
        fields:
          - label: 'Telephone'
            name: 'tel'
            widget: 'string'

