# config.yml

backend:
  name: github
  repo: jndctranslation/landing_page
  branch: master # Branch to update (optionsal; defaults to master)
media_folder: 'img'

collections:
  - name: "website_common_information"
    label: "Website  Common Information"
    files:
      - name: "header_information"
        label: "Header Information"
        file: "_data/header.yml"
        fields:
        - name: 'extra_nav'
          label: 'Extra Navigation Bar'
          widget: 'object'
          fields:
          - name: 'left'
            label: 'Left Side of Extra Navigation Bar'
            widget: 'object'
            fields:
            - {name: 'title', label: 'Title', widget: 'string', required: 'false'}
        - name: 'extra_nav.left.link'
          label: 'haha'
          widget: 'string'
          required: 'false'